api-reference:

  - docs/api_reference/datasets.md:
    - name: Datasets
    - content:
      - torchmeta.datasets:
        - Omniglot
        - MiniImagenet
        - TieredImagenet
        - FC100
        - CIFARFS
        - CUB
        - DoubleMNIST
        - TripleMNIST
        - TCGA
        - Pascal5i

  - docs/api_reference/modules.md:
    - name: Modules
    - content:
      - torchmeta.modules:
        - __all__

  - docs/api_reference/toy.md:
    - name: Toy
    - content:
      - torchmeta.toy:
        - __all__

  - docs/api_reference/transforms.md:
    - name: Transforms
    - content:
      - torchmeta.transforms:
        - Categorical
        - Rotation
        - HorizontalFlip
        - VerticalFlip
        - ClassSplitter
        - WeightedClassSplitter